version: '3.4'

services:
  # TODO: Customize {PROJECT}  
  {PROJECT}:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      # TODO: Customize this sections
      # Ignore local build files (ADD TWO LINES PER EACH CSPROJ /bin /obj)
      - node_modules:/app/src/{PROJECT}/node_modules
      - bin:/app/src/{PROJECT}/bin
      - obj:/app/src/{PROJECT}/obj

      - bin2:/app/src/{PROJECT2}/bin
      - obj2:/app/src/{PROJECT2}/obj

      # Add or remove more lines if needed
      # - bin3:/app/src/{PROJECT3}/bin
      # - bin3:/app/src/{PROJECT3}/bin

    ports:
      - '5001:5000'
    depends_on:
      - db
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      # TODO: Customize if required
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Server=db;Database=master;User=sa;Password=Your_password123;
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
    logging:
      # Enable logging by disabling following line
      driver: none
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  # TODO: Customize according to previous configuration
  node_modules:
  bin:
  obj:
  bin2:
  obj2:
  #bin3:
  #obj3:
  
  sqlserver-data: